version: '3'

services:
  mysql:
    build: mysql
    container_name: db
    ports: 
      - 3307:3306
    networks:
      - net
  nginx:
    build: nginx
    container_name: nginx
    ports: 
      - 8000:80
    networks:
      - net

networks:
  net:
    driver: bridge